[features]
seeds = false
[programs.localnet]
escrow = "AXuUjUsKiZ1goUtaVZYtVBdRk7WGmG4UjrLusjyb8nLF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/madking/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
